### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by raiguard** [raiguard/Factorio-EditorExtensions#1]
0.18 is here, and that means Editor Extensions must be released! There is a bit of work ahead to make the mod ready for consumption:

## To-do:
- [x] Fix potential flaws with the event module
- [x] Update localisations to reflect actual mod features
- [x] Un-hide the editor items and add optional recipes for them so they can be used in cheat mode
- [x] Multiplayer test, release!
